//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamplePlantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GNM_PlantDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GNM_PlantDetails()
        {
            this.TR_MaterialDetails = new HashSet<TR_MaterialDetails>();
        }
    
        public int PlantID { get; set; }
        public string PlantName { get; set; }
        public string PlantLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_MaterialDetails> TR_MaterialDetails { get; set; }
    }
}
