//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamplePlantApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlantModelEntities : DbContext
    {
        public PlantModelEntities()
            : base("name=PlantModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GNM_PlantDetails> GNM_PlantDetails { get; set; }
        public virtual DbSet<GNM_Status> GNM_Status { get; set; }
        public virtual DbSet<GNM_User> GNM_User { get; set; }
        public virtual DbSet<TR_MaterialDetails> TR_MaterialDetails { get; set; }
    }
}
