//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamplePlantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_MaterialDetails
    {
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int StatusID { get; set; }
        public int PlantID { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual GNM_PlantDetails GNM_PlantDetails { get; set; }
        public virtual GNM_Status GNM_Status { get; set; }
        public virtual GNM_User GNM_User { get; set; }
    }
}
